org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248

# Mod properties
mod_id=mekanismae
mod_name=Mekanism AE Bridge
mod_license=MIT
mod_version=0.2.0-beta.3
mod_group_id=io.github.shenfnx.mekanismae

# Required runtime mods
mekanism_version=10.7.19.85
mekanism_dependency_range=[10.7.19,)
ae2_version=19.2.17
appmek_version=1.6.3
guideme_version=21.1.17
