modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="shenFNX"
description='''ME-connected Mekanism processing machines.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanism"
type="required"
versionRange="${mekanism_dependency_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanism_extras"
type="optional"
versionRange="[1.4.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="required"
versionRange="[${ae2_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="appmek"
type="required"
versionRange="[${appmek_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="guideme"
type="required"
versionRange="[${guideme_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[15.10.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19.27.0,)"
ordering="AFTER"
side="CLIENT"
